# Generated by Django 5.1.3 on 2026-08-30 10:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0002_chatmessage_ip_address_userprofile_last_login_ip_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="chatmessage",
            options={
                "ordering": ["-timestamp"],
                "verbose_name": "聊天消息",
                "verbose_name_plural": "聊天消息",
            },
        ),
        migrations.AlterModelOptions(
            name="privatechat",
            options={"verbose_name": "私聊会话", "verbose_name_plural": "私聊会话"},
        ),
        migrations.AlterModelOptions(
            name="privatemessage",
            options={
                "ordering": ["timestamp"],
                "verbose_name": "私聊消息",
                "verbose_name_plural": "私聊消息",
            },
        ),
        migrations.AlterModelOptions(
            name="userloginlog",
            options={
                "ordering": ["-timestamp"],
                "verbose_name": "用户登录日志",
                "verbose_name_plural": "用户登录日志",
            },
        ),
        migrations.AlterModelOptions(
            name="userprofile",
            options={"verbose_name": "用户资料", "verbose_name_plural": "用户资料"},
        ),
        migrations.AddField(
            model_name="chatmessage",
            name="reply_to",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="replies",
                to="chat.chatmessage",
                verbose_name="回复的消息",
            ),
        ),
        migrations.AddField(
            model_name="privatemessage",
            name="reply_to",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="replies",
                to="chat.privatemessage",
                verbose_name="回复的消息",
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="email_verified",
            field=models.BooleanField(default=False, verbose_name="邮箱是否已验证"),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="email_verify_expires",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="验证令牌过期时间"
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="email_verify_token",
            field=models.CharField(
                blank=True, max_length=64, null=True, verbose_name="邮箱验证令牌"
            ),
        ),
        migrations.AlterField(
            model_name="chatmessage",
            name="content",
            field=models.TextField(max_length=2000, verbose_name="消息内容"),
        ),
        migrations.AlterField(
            model_name="chatmessage",
            name="ip_address",
            field=models.GenericIPAddressField(
                blank=True, null=True, verbose_name="发送者IP"
            ),
        ),
        migrations.AlterField(
            model_name="chatmessage",
            name="timestamp",
            field=models.DateTimeField(auto_now_add=True, verbose_name="发送时间"),
        ),
        migrations.AlterField(
            model_name="chatmessage",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="发送用户",
            ),
        ),
        migrations.AlterField(
            model_name="privatechat",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
        ),
        migrations.AlterField(
            model_name="privatechat",
            name="user1",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="chats_as_user1",
                to=settings.AUTH_USER_MODEL,
                verbose_name="用户1",
            ),
        ),
        migrations.AlterField(
            model_name="privatechat",
            name="user2",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="chats_as_user2",
                to=settings.AUTH_USER_MODEL,
                verbose_name="用户2",
            ),
        ),
        migrations.AlterField(
            model_name="privatemessage",
            name="chat",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="messages",
                to="chat.privatechat",
                verbose_name="所属会话",
            ),
        ),
        migrations.AlterField(
            model_name="privatemessage",
            name="content",
            field=models.TextField(max_length=2000, verbose_name="消息内容"),
        ),
        migrations.AlterField(
            model_name="privatemessage",
            name="ip_address",
            field=models.GenericIPAddressField(
                blank=True, null=True, verbose_name="发送者IP"
            ),
        ),
        migrations.AlterField(
            model_name="privatemessage",
            name="is_read",
            field=models.BooleanField(default=False, verbose_name="是否已读"),
        ),
        migrations.AlterField(
            model_name="privatemessage",
            name="sender",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="发送者",
            ),
        ),
        migrations.AlterField(
            model_name="privatemessage",
            name="timestamp",
            field=models.DateTimeField(auto_now_add=True, verbose_name="发送时间"),
        ),
        migrations.AlterField(
            model_name="userloginlog",
            name="ip_address",
            field=models.GenericIPAddressField(
                blank=True, null=True, verbose_name="登录IP"
            ),
        ),
        migrations.AlterField(
            model_name="userloginlog",
            name="success",
            field=models.BooleanField(default=False, verbose_name="是否成功"),
        ),
        migrations.AlterField(
            model_name="userloginlog",
            name="timestamp",
            field=models.DateTimeField(auto_now_add=True, verbose_name="登录时间"),
        ),
        migrations.AlterField(
            model_name="userloginlog",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="用户",
            ),
        ),
        migrations.AlterField(
            model_name="userloginlog",
            name="username_attempted",
            field=models.CharField(max_length=50, verbose_name="尝试用户名"),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="is_banned",
            field=models.BooleanField(default=False, verbose_name="是否封禁"),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="is_muted",
            field=models.BooleanField(default=False, verbose_name="是否禁言"),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="last_active",
            field=models.DateTimeField(auto_now=True, verbose_name="最后活跃时间"),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="last_login_ip",
            field=models.GenericIPAddressField(
                blank=True, null=True, verbose_name="最近登录IP"
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="mute_until",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="禁言到期时间"
            ),
        ),
    ]
