# Generated by Django 5.1.3 on 2026-08-30 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0003_alter_chatmessage_options_alter_privatechat_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="email_verify_exempt",
            field=models.BooleanField(
                default=False, verbose_name="是否豁免邮箱验证（管理员后台设置）"
            ),
        ),
    ]
