# Generated by Django 5.1.3 on 2026-09-03 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0005_chat_upgrade"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatmessage",
            name="is_deleted",
            field=models.BooleanField(default=False, verbose_name="是否撤回"),
        ),
        migrations.AddField(
            model_name="privatemessage",
            name="is_deleted",
            field=models.BooleanField(default=False, verbose_name="是否撤回"),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="signature",
            field=models.CharField(blank=True, max_length=80, verbose_name="个性签名"),
        ),
        migrations.AlterField(
            model_name="chatmessage",
            name="content",
            field=models.TextField(
                blank=True, max_length=2000, verbose_name="消息内容"
            ),
        ),
        migrations.AlterField(
            model_name="privatemessage",
            name="content",
            field=models.TextField(
                blank=True, max_length=2000, verbose_name="消息内容"
            ),
        ),
    ]
