# Generated by Django 5.2.17 on 2026-09-05 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0006_add_signature_isdeleted"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="avatar",
            field=models.ImageField(
                blank=True, null=True, upload_to="avatars/", verbose_name="头像"
            ),
        ),
    ]
