# Generated by Django 5.1.3 on 2026-09-13 11:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0007_userprofile_avatar"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="GroupChat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="群名称")),
                (
                    "description",
                    models.CharField(blank=True, max_length=200, verbose_name="群描述"),
                ),
                (
                    "avatar",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="group_avatars/",
                        verbose_name="群头像",
                    ),
                ),
                (
                    "max_members",
                    models.IntegerField(default=200, verbose_name="最大成员数"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="owned_groups",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="群主",
                    ),
                ),
            ],
            options={
                "verbose_name": "群聊",
                "verbose_name_plural": "群聊",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="GroupMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "content",
                    models.TextField(
                        blank=True, max_length=2000, verbose_name="消息内容"
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(auto_now_add=True, verbose_name="发送时间"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="是否撤回"),
                ),
                (
                    "attachment",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="group_attachments/%Y/%m/%d/",
                        verbose_name="附件",
                    ),
                ),
                (
                    "attachment_name",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="附件原始文件名"
                    ),
                ),
                (
                    "attachment_type",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="附件类型"
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="chat.groupchat",
                        verbose_name="所属群",
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="发送者",
                    ),
                ),
            ],
            options={
                "verbose_name": "群消息",
                "verbose_name_plural": "群消息",
                "ordering": ["timestamp"],
            },
        ),
        migrations.CreateModel(
            name="GroupMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("owner", "群主"),
                            ("admin", "管理员"),
                            ("member", "普通成员"),
                        ],
                        default="member",
                        max_length=10,
                        verbose_name="角色",
                    ),
                ),
                (
                    "nickname",
                    models.CharField(blank=True, max_length=30, verbose_name="群昵称"),
                ),
                (
                    "joined_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="加入时间"),
                ),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="members",
                        to="chat.groupchat",
                        verbose_name="所属群",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="group_memberships",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="成员",
                    ),
                ),
            ],
            options={
                "verbose_name": "群成员",
                "verbose_name_plural": "群成员",
                "ordering": ["-role", "joined_at"],
                "unique_together": {("group", "user")},
            },
        ),
    ]
