# Generated by Django 5.1.3 on 2026-09-13 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0008_groupchat_groupmessage_groupmember"),
    ]

    operations = [
        migrations.AddField(
            model_name="groupchat",
            name="announcement",
            field=models.TextField(blank=True, default="", verbose_name="群公告"),
        ),
    ]
