# Generated by Django 5.1.3 on 2026-09-15 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0009_groupchat_announcement"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="custom_id",
            field=models.CharField(
                blank=True,
                max_length=20,
                null=True,
                unique=True,
                verbose_name="自定义ID",
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="is_admin_panel",
            field=models.BooleanField(default=False, verbose_name="后台管理权限"),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="user_title",
            field=models.CharField(
                blank=True, max_length=30, null=True, verbose_name="用户头衔"
            ),
        ),
    ]
