# Generated by Django 5.2.17 on 2026-09-20 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0014_forward_mention"),
    ]

    operations = [
        migrations.AddField(
            model_name="privatechat",
            name="user1_hidden",
            field=models.BooleanField(
                default=False, verbose_name="用户1是否已删除会话(单方隐藏)"
            ),
        ),
        migrations.AddField(
            model_name="privatechat",
            name="user1_muted",
            field=models.BooleanField(default=False, verbose_name="用户1是否免打扰"),
        ),
        migrations.AddField(
            model_name="privatechat",
            name="user1_pinned",
            field=models.BooleanField(default=False, verbose_name="用户1是否置顶"),
        ),
        migrations.AddField(
            model_name="privatechat",
            name="user2_hidden",
            field=models.BooleanField(
                default=False, verbose_name="用户2是否已删除会话(单方隐藏)"
            ),
        ),
        migrations.AddField(
            model_name="privatechat",
            name="user2_muted",
            field=models.BooleanField(default=False, verbose_name="用户2是否免打扰"),
        ),
        migrations.AddField(
            model_name="privatechat",
            name="user2_pinned",
            field=models.BooleanField(default=False, verbose_name="用户2是否置顶"),
        ),
        migrations.AddField(
            model_name="privatemessage",
            name="deleted_by_sender",
            field=models.BooleanField(default=False, verbose_name="发送者已单方删除"),
        ),
        migrations.AlterField(
            model_name="privatechat",
            name="is_muted",
            field=models.BooleanField(
                default=False, verbose_name="是否免打扰(兼容旧数据)"
            ),
        ),
        migrations.AlterField(
            model_name="privatechat",
            name="is_pinned",
            field=models.BooleanField(
                default=False, verbose_name="是否置顶(兼容旧数据)"
            ),
        ),
    ]
