# Generated by Django 5.2.17 on 2026-09-25 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0015_privatechat_user1_hidden_privatechat_user1_muted_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="groupchat",
            name="join_mode",
            field=models.CharField(
                choices=[("open", "自由加入"), ("approval", "需审核")],
                default="open",
                max_length=10,
                verbose_name="入群方式",
            ),
        ),
        migrations.AddField(
            model_name="groupchat",
            name="join_pin",
            field=models.CharField(
                blank=True,
                max_length=16,
                null=True,
                verbose_name="群主PIN码（输入正确PIN可直接入群）",
            ),
        ),
        migrations.CreateModel(
            name="GroupJoinRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待处理"),
                            ("approved", "已通过"),
                            ("rejected", "已拒绝"),
                        ],
                        default="pending",
                        max_length=10,
                        verbose_name="状态",
                    ),
                ),
                (
                    "message",
                    models.CharField(blank=True, max_length=200, verbose_name="申请留言"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="申请时间"),
                ),
                (
                    "handled_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="处理时间"),
                ),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="join_requests",
                        to="chat.groupchat",
                        verbose_name="所属群",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="group_join_requests",
                        to="auth.user",
                        verbose_name="申请人",
                    ),
                ),
            ],
            options={
                "verbose_name": "入群申请",
                "verbose_name_plural": "入群申请",
                "ordering": ["-created_at"],
                "unique_together": {("group", "user")},
            },
        ),
    ]
