# Generated by Django 5.1.3 on 2026-09-13 14:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("panel", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="adminloginlog",
            options={
                "ordering": ["-timestamp"],
                "verbose_name": "管理员登录日志",
                "verbose_name_plural": "管理员登录日志",
            },
        ),
        migrations.AlterModelOptions(
            name="adminuser",
            options={"verbose_name": "管理员账号", "verbose_name_plural": "管理员账号"},
        ),
        migrations.AlterModelOptions(
            name="ipblacklist",
            options={"verbose_name": "IP黑名单", "verbose_name_plural": "IP黑名单"},
        ),
        migrations.AlterField(
            model_name="adminloginlog",
            name="admin",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="panel.adminuser",
                verbose_name="管理员",
            ),
        ),
        migrations.AlterField(
            model_name="adminloginlog",
            name="ip_address",
            field=models.GenericIPAddressField(verbose_name="登录IP"),
        ),
        migrations.AlterField(
            model_name="adminloginlog",
            name="success",
            field=models.BooleanField(default=False, verbose_name="是否成功"),
        ),
        migrations.AlterField(
            model_name="adminloginlog",
            name="timestamp",
            field=models.DateTimeField(auto_now_add=True, verbose_name="登录时间"),
        ),
        migrations.AlterField(
            model_name="adminloginlog",
            name="username_attempted",
            field=models.CharField(max_length=50, verbose_name="尝试用户名"),
        ),
        migrations.AlterField(
            model_name="adminuser",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
        ),
        migrations.AlterField(
            model_name="adminuser",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="是否启用"),
        ),
        migrations.AlterField(
            model_name="adminuser",
            name="password_hash",
            field=models.CharField(max_length=255, verbose_name="密码哈希"),
        ),
        migrations.AlterField(
            model_name="adminuser",
            name="role",
            field=models.CharField(
                choices=[("super", "超级管理员"), ("normal", "普通管理员")],
                default="normal",
                max_length=10,
                verbose_name="角色",
            ),
        ),
        migrations.AlterField(
            model_name="adminuser",
            name="username",
            field=models.CharField(max_length=50, unique=True, verbose_name="用户名"),
        ),
        migrations.AlterField(
            model_name="ipblacklist",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
        ),
        migrations.AlterField(
            model_name="ipblacklist",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="panel.adminuser",
                verbose_name="创建者",
            ),
        ),
        migrations.AlterField(
            model_name="ipblacklist",
            name="ip_address",
            field=models.GenericIPAddressField(unique=True, verbose_name="IP地址"),
        ),
        migrations.AlterField(
            model_name="ipblacklist",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="是否生效"),
        ),
        migrations.AlterField(
            model_name="ipblacklist",
            name="reason",
            field=models.CharField(blank=True, max_length=255, verbose_name="封禁原因"),
        ),
    ]
